environment:
  matrix:
    # does not work with sw at the moment
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #platform: Win32
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win32
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #platform: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      platform: Win64

configuration:
  - Release

build_script:
  - echo 123

  -
    ps: $wc = New-Object 'System.Net.WebClient'
  -
    ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))
