name: sw

on:
  push:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - name: install
      run: |
        brew update
        brew install flex bison gcc llvm m4
    #- run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - run: ./sw --version
    - name: build
      run: |
        export PATH="/opt/homebrew/opt/m4/bin:$PATH"
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
        export PATH="/opt/homebrew/opt/flex/bin:$PATH"
        export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
        export PATH="/opt/homebrew/opt/gcc/bin:$PATH"
        #./sw build -compiler gcc-14 -sfc
        ./sw build -compiler clang --trace -j 1
        
